In [1]:
import pandas as pd

In [7]:
# df=pd.DataFrame([[2,6,9],[6,1,4],[9,2,7]],columns=["A","B","C"])
df=pd.DataFrame([["Zunaisha",22,"girl"],["Eman",20,"girl"],["Abdul Hadi",15,"boy"]],columns=["Names","Age","Gender"])

In [15]:
# df.head()         #shows first 5 rows
# df.head(1)
# df.tail()           #shows last 5 rows
df.tail(1)

        Names  Age Gender
2  Abdul Hadi   15    boy

In [16]:
df=pd.DataFrame([["Zunaisha",22,"girl"],["Eman",20,"girl"],["Abdul Hadi",15,"boy"]],columns=["Names","Age","Gender"])

In [21]:
df.columns           #column names

Index(['Names', 'Age', 'Gender'], dtype='object')

In [23]:
# df.index
df.index.to_list()

[0, 1, 2]

In [39]:
df=pd.DataFrame([["Zunaisha",22,"girl"],["Eman",20,"girl"],["Abdul Hadi",15,"boy"]],columns=["Names","Age","Gender"],index=["first","second","third"])

In [40]:
df.head()

             Names  Age Gender
first     Zunaisha   22   girl
second        Eman   20   girl
third   Abdul Hadi   15    boy

In [41]:
df.index

Index(['first', 'second', 'third'], dtype='object')

In [42]:
df.index.tolist()

['first', 'second', 'third']

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, first to third
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Names   3 non-null      object
 1   Age     3 non-null      int64
 2   Gender  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 96.0+ bytes

In [48]:
df.describe()              #details of int column

             Age
count   3.000000
mean   19.000000
std     3.605551
min    15.000000
25%    17.500000
50%    20.000000
75%    21.000000
max    22.000000

In [50]:
df.nunique()               #unique values
# df['Names'].nunique()
# df['Gender'].nunique()

Names     3
Age       3
Gender    2
dtype: int64

In [54]:
df.shape         #(rows,columns)
# df.size          #total elements

(3, 3)